# Connessione al DB
spring.datasource.url=jdbc:postgresql://localhost:5432/noleggio_db
spring.datasource.username=postgres
spring.datasource.password=admin

# Hibernate - JPA
# 'update' crea o aggiorna le tabelle automaticamente in base alle tue classi @Entity
spring.jpa.hibernate.ddl-auto=update

# Dialetto specifico per PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Logging (utile per le ripetizioni: vedi l'SQL che Spring genera per te)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true